apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nebula-west-ca
  namespace: gitlab
spec:
  isCA: true
  commonName: nebula-west-ca
  secretName: nebula-west-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: gitlab-issuer
  namespace: gitlab
spec:
  ca:
    secretName: nebula-west-tls